# Generated by Django 3.2.3 on 2022-03-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('vehicleId', models.CharField(max_length=100, unique=True)),
                ('fuelConsumption', models.IntegerField(blank=True, default=0, null=True)),
                ('fuelConsumed', models.IntegerField(blank=True, default=0, null=True)),
                ('distanceTraveled', models.IntegerField(blank=True, default=0, null=True)),
                ('currentCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityDistance',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('distance', models.IntegerField(blank=True, default=0)),
                ('cityFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityFrom', to='api.city')),
                ('cityTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityTo', to='api.city')),
            ],
        ),
    ]
