# Generated by Django 3.2.3 on 2022-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydistance',
            name='distance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuelConsumption',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
